terrorctf/website/src/app/models/auth.py
from flask_login import UserMixin
from app.models.challenges import Problem
from app.extensions import db

team_problems_solved = db.Table(
    'team_problems_solved',
    db.Column('team_id', db.Integer, db.ForeignKey('team.id')),
    db.Column('problem_id', db.Integer, db.ForeignKey('problem.id')),
)

class Team(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    shareable_id = db.Column(db.String(32))
    solved_problems = db.relationship(
        'Problem',
        secondary=team_problems_solved,
        backref=db.backref('teams_that_solved', lazy='dynamic'),
        lazy='dynamic'
    )

    def __repr__(self):
        return f'<Team "{self.name}">'


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

    team_id = db.Column(db.Integer, db.ForeignKey('team.id'), name='fk_user_team_id')
    team = db.relationship('Team', backref='members')

terrorctf/website/src/app/models/challenges.py
from sqlalchemy import CheckConstraint
from app.extensions import db


class Problem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.Text)
    category = db.Column(db.String(50))

    __table_args__ = (
        CheckConstraint(
            category.in_(['crypto', 'web', 'pwn', 'rev', 'misc']),
            name='valid_problem_category'
        ),
    )

    # the Team model will make a field called teams_that_solved

    def __repr__(self):
        return f'<Problem "{self.name}">'
    

terrorctf/website/src/app/__init__.py
import os
from flask import Flask
from config import Config, DevelopmentConfig
from app.extensions import db, migrate, login_manager


def create_app(config_class=Config):
    app = Flask(__name__)
    is_production = bool(int(os.getenv("prod", "0")))

    if not is_production:
        app.config.from_object(DevelopmentConfig)
    else:
        app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    migrate.init_app(app)

    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.challenges import bp as challenges_bp
    app.register_blueprint(challenges_bp)

    return app


@login_manager.user_loader
def load_user(user_id):
    from app.models.auth import User
    return User.query.filter(User.id == int(user_id)).first()

terrorctf/website/src/app/challenges/__init__.py
from flask import Blueprint

bp = Blueprint('challenges', __name__)


from app.challenges import routes

terrorctf/website/src/app/challenges/routes.py
import os
from pathlib import Path
import random
import tomllib
from flask import render_template, request
from app.challenges import bp
from app.models.challenges import Problem
from app.util.fileutils import copy_file, delete_folder_contents


@bp.route('/list')
def list():

    return render_template("challenges/list.html")

@bp.route('/iafijoa/load-challenges', methods=['GET', 'POST'])
def load_challenges():
    """This may be very prone to breaking. Be cautious."""

    if request.method == 'POST':
        appdir = Path(os.path.abspath(os.path.dirname(__file__)))
        srcdir = appdir.parent.absolute()
        webdir = srcdir.parent.absolute()
        rootdir = webdir.parent.absolute()

        downloads_dir = appdir / "static" / "downloads"
        problems_dir = rootdir / "problems"

        delete_folder_contents(downloads_dir)

        problems_to_add = []
        # iterate over all the categories
        for category_dir in problems_dir.glob("*/"):
            if "rev" not in category_dir.name    or \
            "web" not in category_dir.name    or \
            "pwn" not in category_dir.name    or \
            "misc" not in category_dir.name   or \
            "crypto" not in category_dir.name:
                continue
            
            # iterate over each problem in each category
            for problem_dir in category_dir.glob("*/"):
                with open(problem_dir / "challenge.toml", "rb") as f:
                    problem_toml = tomllib.load(f)
                    section_challenge = problem_toml.get("challenge")
                    section_download = problem_toml.get("download")
                    section_server = problem_toml.get("server")
                    section_netcat = section_server.get("netcat") if section_server is not None else None

                    problem_title = section_challenge.get("title")
                    problem_description_filename = section_challenge.get("description", "No description provided.")
                    problem_flag = section_challenge.get("flag")
                    problem_points = section_challenge.get("points")

                    if section_challenge  is None \
                        or problem_title  is None \
                        or problem_flag   is None \
                        or problem_points is None:
                        # TODO: Add logging that the problem was invalid
                        continue
                    
                    problem_description_file: Path = problem_dir / problem_description_filename

                    description_filename = "description" + problem_title + "_" + str(random.randint(1000, 9999))

                    # copy the file to the downloads directory
                    copy_file(
                        problem_description_file,
                        downloads_dir / description_filename
                    )
                    return "done"


                    # Problem(
                    #     name=problem_title,
                        
                    # )


terrorctf/website/src/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

terrorctf/website/src/app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/')
def home():
    return render_template("home.html")

terrorctf/website/src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
        
        {% block head %} {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        {% if not current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                            </li>
                        {% else %}
                            {% if current_user.team %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('challenges.list') }}">Challenges</a>
                            </li>
                            {% endif%}

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{{ url_for('auth.account') }}">View Account</a></li>
                                    <li><a class="dropdown-item" href="{{ url_for('auth.account') }}?action=create-team">Create a Team</a></li>
                                    <li><a class="dropdown-item" href="{{ url_for('auth.account') }}?action=join-team">Join a Team</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            </nav>

        <div class="content">
            {% block content %} {% endblock %}
        </div>
        
        {% block modals %} {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        {% block js %} {% endblock %}


    </body>
</html>

terrorctf/website/src/app/templates/home.html
{% extends 'base.html' %}

{% block title %}TerrorCTF{% endblock %}

{% block content %}
    <h1>TerrorCTF</h1>
    <h2>Contest Information</h2>
    <p>
        <b>Start</b>: Saturday, February 3rd, 2024 at 2pm PST
    </p>
    <p>
        <b>End</b>:   Sunday, February 4th, 2024 at 5pm PST
    </p>
    <p>
        <b>Discord Server</b>: <a href="https://discord.gg/3AHZweXTCc">https://discord.gg/3AHZweXTCc</a>
    </p>

    <h2>Contest Rules</h2>
    <ol>
        <li>Don't talk with other teams about the problems during the contest (i.e. don't cheat).</li>
        <li>Teams can have up to 4 people.</li>
        <li>Don't attempt to break the main website itself.</li>
        <li>Don't attempt to break out of the jail on the images.</li>
        <li>Have fun!</li>
    </ol>

    <h2>How to Participate</h2>
    <p>
        Talk with up to 3 other people to form a team (or you can solo but it might not be as fun). Each person should create an account. Then, one person should go to their profile, then press "Create a Team". A team ID will be generated. Other participants can go their profile, press "Join a Team", and type in that team ID to join the team.
    </p>
    <p>
        On the day of the contest, press the "problems" link. You will see all the problems for the contest.
    </p>
{% endblock %}